# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0751c5df5da0c8388e4eaa030c34a6dbf7c9f6d0042ac3842e46dba3ff50bc2617145a2ca0abb6b8797a5bb30d3613087b1beef77142d3dab16a6f4f9cc33079

test:
  secret_key_base: fdcaf2e92e9735d368e225e1c5e1694307378afc60f90b4783f6dc24da27ac0232bd16b841d4842c9115742e389604f48e3e10f8a386f69648872c5a7122ade8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
